# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  migrate:
    cmds:
      - sqlite3 appdb.sqlite < internal/migrations/schema.sql

  migrate:clean:
    cmds:
      - rm -f appdb.sqlite
      - sqlite3 appdb.sqlite < internal/migrations/schema.sql
      
