# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  migrate:
    cmds:
      - sqlite3 app.db < internal/migrations/schema.sql

  migrate:clean:
    cmds:
      - rm -f app.db
      - sqlite3 app.db < internal/migrations/schema.sql
      
