# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  migrate:
    cmds:
      - sqlite3 app.db < internal/migrations/schema.sql

  migrate:clean:
    cmds:
      - rm -f app.db
      - sqlite3 app.db < internal/migrations/schema.sql
      
  build:
    cmds:
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server cmd/main.go
