// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Depotevent struct {
	ID         int64
	Completion float64
	Time       int64
	Marketid   int64
	RawText    string
}

type Dockevent struct {
	ID          int64
	Time        int64
	Marketid    string
	Systemname  string
	Stationname string
}

type Event struct {
	ID           int64
	Time         int64
	Completion   float64
	Marketid     int64
	Systemname   string
	Stationname  string
	RawResources string
}

type Resource struct {
	ID       int64
	Eventid  int64
	Name     string
	Required int64
	Provided int64
	Diff     int64
	Payment  int64
	Time     int64
}

type Resourceid struct {
	ID   int64
	Name string
}
