// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Event struct {
	ID      interface{}
	RawText string
	Time    int64
}

type Resource struct {
	ID       interface{}
	Name     string
	Required int64
	Provided int64
	Diff     int64
	Payment  int64
	Time     int64
}

type Resourceid struct {
	ID   int64
	Name string
}
